#!/usr/bin/python3
# emacs: -*- mode: python; py-indent-offset: 4; indent-tabs-mode: nil -*-
# vi: set ft=python sts=4 ts=4 sw=4 et:
"""
  Yaroslav Halchenko
  web:     http://www.onerussian.com
  e-mail:  yoh@onerussian.com

 DESCRIPTION (NOTES):

    See README.rst shipped with this tool.
    "Homepage" for the tool is http://github.com/yarikoptic/svgtune

 LICENSE:

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the
  Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
  MA 02110-1301, USA.

 On Debian system see /usr/share/common-licenses/GPL for the full license.
"""
__author__ = 'Yaroslav Halchenko'
__version__ = (0, 4, 0)
__copyright__ = 'Copyright (c) 2009-2026 Yaroslav Halchenko'
__license__ = 'GPL'

import math
import os, re
import subprocess
from lxml import etree
from optparse import OptionParser

# Setup rudimentary logging
import logging
lgr = logging.getLogger("svgtune")
lgr.addHandler(logging.StreamHandler())

NS = {
    'svg': 'http://www.w3.org/2000/svg',
    'inkscape': 'http://www.inkscape.org/namespaces/inkscape',
    'xlink': 'http://www.w3.org/1999/xlink',
}

# Inkscape executable to use for previews and bounding boxes (%crop)
INKSCAPE = os.environ.get('INKSCAPE', 'inkscape')

# Attributes identifiers (id=, label=, href=) are matched against
IDENTIFIER_ATTRS = {
    'id': ['id'],
    'label': ['{%s}label' % NS['inkscape']],
    'href': ['{%s}href' % NS['xlink'], 'href'],
}

# SVG elements which are never rendered directly, so there is no point to
# hide or prune them
NON_RENDERED = set('{%s}%s' % (NS['svg'], t) for t in (
    'defs', 'metadata', 'title', 'desc', 'style', 'script', 'symbol',
    'clipPath', 'mask', 'marker', 'pattern', 'linearGradient',
    'radialGradient', 'filter', 'font', 'font-face', 'cursor', 'view'))

# Elements which render (a copy of) the element they refer to
CLONE_ELEMENTS = set('{%s}%s' % (NS['svg'], t) for t in ('use', 'feImage'))

# Elements within which text (tail of children) matters
TEXT_ELEMENTS = set('{%s}%s' % (NS['svg'], t) for t in (
    'text', 'tspan', 'textPath', 'a', 'flowRoot', 'flowPara', 'flowSpan',
    'flowDiv'))

# Definitions which have global effect or are referenced not by #id (but
# e.g. by font-family), thus never pruned
DEFS_KEEP = set('{%s}%s' % (NS['svg'], t) for t in (
    'style', 'script', 'font', 'font-face', 'color-profile'))

# Absolute length, e.g. '210mm'
LENGTH_RE = re.compile(
    r'^\s*([-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?)\s*([a-zA-Z]*)\s*$')

# Anything which looks like a reference (#id) in attribute values or CSS
REF_RE = re.compile(r'#([^\s\'"(),;#]+)')


def split2(l, msg, sep=' '):
    """Split l into 2 pieces using ' ' as a separator
    """
    p = [x.strip() for x in (l.split(sep, 1)) if x != '']

    if len(p) != 2:
        raise ValueError(msg + '. Got %s for "%s"' % (p, l))

    return p


def replace_key(attr_value, key, value):
    """Replace value for a given key

       If key is not found, new one is added
    """
    v = attr_value.split(';')
    changed = False
    newval = '%s:%s' % (key, value)
    for i in range(len(v)):
        if v[i].startswith(key + ':'):
            v[i] = newval
            changed = True
    if not changed:
        # Wasn't found -- add one
        v += [newval]
    return ';'.join(x for x in v if x.strip())


def change_attr(el, attr, values):
    """Change values listed within attribute attr
    """
    v = el.attrib.get(attr, '')
    changed = False
    for value in values.split(';'):
        k, newv = split2(value, "Each value must be in the form x:y", ":")
        v = replace_key(v, k, newv)
    if v == '':                         # there were no such yet
        v = "%s:%s" % (k, newv)
    #print "Changing %s : %s, got %s" % (attr, values, str(v))
    el.attrib[attr] = v


def get_style(el, key):
    """Return effective value of a property set directly on the element

    style attribute takes precedence over presentation attribute
    """
    value = el.attrib.get(key)
    for item in el.attrib.get('style', '').split(';'):
        if ':' in item:
            k, v = item.split(':', 1)
            if k.strip() == key:
                value = v.strip()
    return value


def verbose(level, str_):
    if level <= options.verbose:
        lgr.info(" "*(level-1) + str_)


def version():
    print("svgtune v" + ".".join(map(str, __version__)))
    raise SystemExit


def process_options(params, options):
    # For now simply split by space
    option_values = params.split(' ')
    for option_value in option_values:
        t = option_value.split('=', 1)
        option = t[0]
        value = t[1] if len(t) > 1 else None
        if option in ["previews", "nosvgs"]:
            # if only said "previews" assume that we want them
            if value is None:
                value = True
            setattr(options, option, bool(value))
        else:
            raise ValueError("Unknown option %s" % option)
    pass


def load_svg(svgfile):
    verbose(1, "Processing file %s for tuning" % svgfile)
    # huge_tree to not choke on large embedded (base64) images
    svgdoc = etree.parse(svgfile, etree.XMLParser(huge_tree=True))
    svg = svgdoc.getroot()

    dname = '%s_tuned' % os.path.splitext(svgfile)[0]
    try:
        os.mkdir(dname)
    except:
        pass # if directory exists or hell with everything
    return svg, svgdoc, dname


def write_svg(svgdoc, f):
    """Write the document as is.

    No pretty printing, since it might inject whitespace into text elements,
    which would change the rendering (e.g. under xml:space="preserve")
    """
    f.write(etree.tostring(svgdoc, xml_declaration=True, encoding='UTF-8'))


def find_victims(svg, elem, identifier):
    """Find elements matching an identifier such as id=foo or label:re=^bar

    elem is the kind of elements to consider: 'layer', 'g', 'text', or 'any'.
    Unless a regular expression is used, a single element must match.
    """
    key, value = split2(identifier,
                        "Identifier must be in the form key=value", '=')
    use_re = key.endswith(':re')
    if use_re:
        key = key[:-3]
    if key not in IDENTIFIER_ATTRS:
        raise ValueError("Unknown identifier %s" % identifier)

    if elem == 'any':
        candidates = svg.iterdescendants(etree.Element)
    elif elem == 'layer':
        candidates = (
            e for e in svg.iter('{%s}g' % NS['svg'])
            if e.get('{%s}groupmode' % NS['inkscape']) == 'layer')
    else:
        candidates = svg.iter('{%s}%s' % (NS['svg'], elem))

    regexp = re.compile(value) if use_re else None

    def matches(el):
        for attr in IDENTIFIER_ATTRS[key]:
            if regexp.search(el.get(attr, '')) if regexp \
                    else el.get(attr) == value:
                return True
        return False

    victims = [e for e in candidates if matches(e)]
    lgr.debug("Found %d victims for %r among %s elements"
              % (len(victims), identifier, elem))
    if not victims:
        raise ValueError("Cannot find any victim for '%s'" % identifier)
    elif len(victims) > 1 and not use_re:
        raise ValueError(
            "We should get a single victim for %s "
            "but got %d of them" % (identifier, len(victims)))
    return victims


def is_rendered(el):
    """Whether element is an SVG element which might get rendered"""
    return (isinstance(el.tag, str)
            and el.tag.startswith('{%s}' % NS['svg'])
            and el.tag not in NON_RENDERED)


def remove_element(el):
    """Remove element from the tree

    Meaningful text after it, and global definitions (DEFS_KEEP) within it,
    are preserved.
    """
    parent = el.getparent()
    for keep in [e for e in el.iterdescendants() if e.tag in DEFS_KEEP]:
        if el in keep.iterancestors():  # i.e. not moved already with a parent
            keep.tail = None
            el.addprevious(keep)
    tail = el.tail
    if tail and (tail.strip() or parent.tag in TEXT_ELEMENTS):
        prev = el.getprevious()
        if prev is not None:
            prev.tail = (prev.tail or '') + tail
        else:
            parent.text = (parent.text or '') + tail
    parent.remove(el)


def only(svg, victims):
    """Leave visible only the victims (and their ancestors)

    All other renderable elements which are siblings of the victims or of
    their ancestors get hidden, or moved into <defs> if a visible clone
    refers to them (which would get hidden otherwise as well).  The victims
    and their ancestors get shown.  Anything within the victims is left
    untouched.  Victims which are not rendered (e.g. in <defs>) are ignored.
    """
    rendered = set(
        v for v in victims
        if is_rendered(v) and all(is_rendered(a) for a in v.iterancestors()))
    if not rendered:
        raise ValueError("None of the selected elements is rendered")
    # those within other victims are left untouched
    victims = set(v for v in rendered
                  if not any(a in rendered for a in v.iterancestors()))
    ancestors = set()
    for v in victims:
        ancestors.update(v.iterancestors())
    for el in victims | ancestors:
        if el is not svg:
            change_attr(el, 'style', 'display:inline')
    # in document order, so the result does not change from run to run
    to_hide = [e for e in svg.iter(etree.Element)
               if e.getparent() in ancestors and e not in victims
               and e not in ancestors and is_rendered(e)]
    hidden = set(e for h in to_hide for e in h.iter())
    refs = collect_refs(svg)
    for el in to_hide:
        if any(r.tag in CLONE_ELEMENTS and r not in hidden and not any(
                get_style(a, 'display') == 'none'
                for a in [r] + list(r.iterancestors()))
               for r in refs.get(el.get('id'), ())):
            get_defs(svg).append(el)
        else:
            change_attr(el, 'style', 'display:none')


def get_defs(svg):
    """Return (the first) <defs> of the document, creating it if needed"""
    defs = svg.find('{%s}defs' % NS['svg'])
    if defs is None:
        defs = etree.Element('{%s}defs' % NS['svg'])
        svg.insert(0, defs)
    return defs


def collect_refs(svg):
    """Return {id: [elements referring to it]}"""
    refs = {}
    for el in svg.iter(etree.Element):
        values = [v for v in el.attrib.values() if '#' in v]
        if el.tag == '{%s}style' % NS['svg'] and el.text:
            values.append(el.text)
        for v in values:
            for id_ in REF_RE.findall(v):
                refs.setdefault(id_, []).append(el)
    return refs


def prune(svg):
    """Remove hidden elements and then unused definitions

    Elements are kept if they (or any of their descendants) are referenced
    from elsewhere (e.g. by a clone or a textPath).  Repeated until nothing
    is left to remove, since removal of one element might leave others
    unreferenced.
    """
    def referenced(el, refs):
        subtree = set(el.iter(etree.Element))
        return any(r not in subtree
                   for e in subtree for r in refs.get(e.get('id'), ()))

    nremoved = 0
    while True:
        refs = collect_refs(svg)
        victims = []

        def collect_hidden(el):
            for child in el:
                if not is_rendered(child):
                    continue
                if get_style(child, 'display') == 'none':
                    if not referenced(child, refs):
                        victims.append(child)
                else:
                    collect_hidden(child)

        collect_hidden(svg)
        for defs in svg.iter('{%s}defs' % NS['svg']):
            for child in defs:
                if (isinstance(child.tag, str) and child.tag not in DEFS_KEEP
                        and not referenced(child, refs)):
                    victims.append(child)
        if not victims:
            break
        for el in victims:
            remove_element(el)
        nremoved += len(victims)
    verbose(2, "Pruned %d elements" % nremoved)


def get_viewbox(svg):
    """Return viewBox [x, y, w, h] of the document, or None if there is none"""
    vb = svg.get('viewBox')
    if not vb:
        return None
    vb = [float(x) for x in re.split(r'[\s,]+', vb.strip())]
    if len(vb) != 4 or vb[2] <= 0 or vb[3] <= 0:
        raise ValueError("Cannot handle viewBox %r" % svg.get('viewBox'))
    return vb


def fmt(v):
    """Format a number compactly but precisely enough"""
    s = ('%.6f' % v).rstrip('0').rstrip('.')
    return '0' if s == '-0' else s


def query_bboxes(svgdoc, elements, svgfile):
    """Return visual bounding boxes (x, y, w, h) of elements in user units

    Computed by Inkscape (so text is accounted for properly) for the current
    state of the document.  Elements without a bounding box (e.g. empty
    groups) get None.
    """
    svg = svgdoc.getroot()
    vb = get_viewbox(svg)
    tmpid_elements = []
    for i, el in enumerate(elements):
        if not el.get('id'):
            el.set('id', 'svgtune-tmp-%d' % i)
            tmpid_elements.append(el)
    ids = [el.get('id') for el in elements]
    size = {a: svg.get(a) for a in ('width', 'height')}
    try:
        if vb:
            # so Inkscape reports in user units (relative to viewBox origin)
            svg.set('width', fmt(vb[2]))
            svg.set('height', fmt(vb[3]))
        data = etree.tostring(svgdoc, xml_declaration=True, encoding='UTF-8')
    finally:
        for el in tmpid_elements:
            del el.attrib['id']
        for a, v in size.items():
            if v is None:
                svg.attrib.pop(a, None)
            else:
                svg.set(a, v)
    verbose(3, "Querying bounding boxes using Inkscape")
    # from the directory of the file, so relative links (images) still work
    res = subprocess.run([INKSCAPE, '--pipe', '--query-all'], input=data,
                         stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                         cwd=os.path.dirname(os.path.abspath(svgfile)))
    if res.returncode:
        raise RuntimeError("%s --query-all failed: %s"
                           % (INKSCAPE, res.stderr.decode(errors='replace')))
    found = {}
    for line in res.stdout.decode().splitlines():
        rec = line.rsplit(',', 4)
        if len(rec) == 5:
            try:
                found[rec[0]] = [float(x) for x in rec[1:]]
            except ValueError:
                pass
    x0, y0 = vb[:2] if vb else (0., 0.)
    # Inkscape reports only 6 significant digits, so do not pretend more
    # (relative to the size of the document)
    ndigits = max(0, 5 - int(math.floor(math.log10(max(vb[2:]))))) \
        if vb else 3

    def r(v):
        return round(v, ndigits) + 0.  # + 0. to avoid -0.0
    return [None if b is None else
            (r(b[0] + x0), r(b[1] + y0), r(b[2]), r(b[3]))
            for b in map(found.get, ids)]


def set_viewbox(svg, x, y, w, h):
    """Change visible area of the document, keeping its scale and units"""
    if w <= 0 or h <= 0:
        raise ValueError("Got non-positive size of the area: %s x %s" % (w, h))
    vb = get_viewbox(svg)
    if vb is None:
        # user units were px
        svg.set('width', fmt(w))
        svg.set('height', fmt(h))
    else:
        # scale absolute (not % or missing) size
        for attr, new, old in (('width', w, vb[2]), ('height', h, vb[3])):
            m = LENGTH_RE.match(svg.get(attr, ''))
            if m:
                svg.set(attr,
                        fmt(float(m.group(1)) * new / old) + m.group(2))
    svg.set('viewBox', ' '.join(fmt(v) for v in (x, y, w, h)))
    # pages of multi-page documents (Inkscape >= 1.2) would no longer match
    for page in list(svg.iter('{%s}page' % NS['inkscape'])):
        page.getparent().remove(page)


def crop(svgdoc, params, svgfile):
    """Crop the document to the bounding box of elements, or a given box

    params: space separated list of
      identifiers (id=, label=, ...) -- elements to crop to.  If none given,
                 crop to the visible drawing
      box=x,y,w,h -- explicit area (in user units) to crop to
      margin=m -- margin (in user units) to add around the area
    """
    svg = svgdoc.getroot()
    margin = 0.
    box = None
    identifiers = []
    for param in params.split():
        if param.startswith('margin='):
            margin = float(param[7:])
        elif param.startswith('box='):
            box = [float(x) for x in param[4:].split(',')]
            if len(box) != 4:
                raise ValueError("box= must list x,y,width,height. Got %s"
                                 % param)
        else:
            identifiers.append(param)
    if box and identifiers:
        raise ValueError("Specify either box= or elements to crop to")

    if box is None:
        if identifiers:
            elements = [v for i in identifiers
                        for v in find_victims(svg, 'any', i)]
        else:
            elements = [svg]
        bboxes = [b for b in query_bboxes(svgdoc, elements, svgfile) if b]
        if not bboxes:
            raise ValueError("Could not determine bounding box for %s"
                             % (' '.join(identifiers) or 'the drawing'))
        x0 = min(b[0] for b in bboxes)
        y0 = min(b[1] for b in bboxes)
        x1 = max(b[0] + b[2] for b in bboxes)
        y1 = max(b[1] + b[3] for b in bboxes)
        box = [x0, y0, x1 - x0, y1 - y0]

    x, y, w, h = box
    verbose(2, "Cropping to %s with margin %s" % (box, margin))
    set_viewbox(svg, x - margin, y - margin, w + 2 * margin, h + 2 * margin)


def parse_cmdline():
    parser = OptionParser(usage="%prog [options] inputfile.svgtune",
                          version="%prog version "
                                  + ".".join([str(i) for i in __version__]))
    parser.add_option("-v", action="count", dest="verbose",
                      help="Increase verbosity with multiple -v", default=0)
    parser.add_option("-p", "--previews", action="store_true",
                      dest="previews", help="Store preview png's")
    parser.add_option("--no-svgs", action="store_true",
                      dest="nosvgs", help="Remove 'final' svgs")


    (options_, args) = parser.parse_args()

    if len(args) != 1:
        raise SystemExit(
            "Error: Please provide single input file with instructions.")

    lgr.setLevel(logging.DEBUG if options_.verbose >= 4 else logging.INFO)

    return args[0], options_


def svgtune(ifile, options):
    svg = svgdoc = svgfile = dname = None

    lineno = 0
    try:
        for lineno, line_ in enumerate(open(ifile), 1):
            line = line_.strip()
            if line.startswith('#') or line == '':
                continue
            if line.rstrip() == '%exit':
                break

            # parse out first element
            cmd, _, params = line.partition(' ')
            params = params.strip()
            if cmd in ('%reset', '%prune'):
                if params:
                    raise ValueError("%s takes no parameters" % cmd)
            elif not params and cmd != '%crop':
                raise ValueError("Each line must be 'command parameters'. "
                                 "Got %r" % line)

            if cmd == '%file':
                svgfile = params
                svg, svgdoc, dname = load_svg(svgfile)
                continue
            elif cmd == "%options":
                process_options(params, options)
                continue

            # We must have file loaded by now
            if svg is None:
                svgfile = os.path.splitext(ifile)[0] + '.svg'
                try:
                    svg, svgdoc, dname = load_svg(svgfile)
                except Exception as e:
                    raise RuntimeError(
                        "Tried to load from %s but failed due to %s.\n"
                        "Please provide %%file directive to load the file prior %s "
                        "or have .svg file with the same name as .svgtune."
                        % (svgfile, e, cmd))

            if cmd == '%save':
                ofile = '%s/%s.svg' % (dname, params)
                verbose(1, "Storing into %s" % ofile)
                with open(ofile, 'wb') as f:
                    write_svg(svgdoc, f)
                if options.previews:
                    verbose(3, "Generating preview")
                    subprocess.call(
                        [INKSCAPE, '--export-type=png', '--export-dpi=300',
                         '--export-filename=%s_preview.png'
                         % os.path.splitext(ofile)[0],
                         ofile],
                        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                if options.nosvgs:
                    verbose(4, "Removing generated svg")
                    os.remove(ofile)
                continue
            elif cmd == '%reset':
                verbose(2, "Reloading %s" % svgfile)
                svg, svgdoc, dname = load_svg(svgfile)
                continue
            elif cmd == '%only':
                only(svg, [v for identifier in params.split()
                           for v in find_victims(svg, 'any', identifier)])
                continue
            elif cmd == '%crop':
                crop(svgdoc, params, svgfile)
                continue
            elif cmd == '%prune':
                prune(svg)
                continue

            #
            # Figure out the victims for changes -- victims
            if cmd == 'layers':
                changes = params
                victims = svg.findall('.//{%s}g[@{%s}groupmode="layer"]'
                                      % (NS['svg'], NS['inkscape']))
            elif cmd in ['layer', 'g', 'text', 'any']:
                # parse out first element
                identifier, changes = split2(params,
                           "For each layer or g you must list id or label + changes")
                victims = find_victims(svg, cmd, identifier)
            else:
                raise ValueError("Unknown command '%s'." % cmd)

            #
            # Figure out the actual changes to take and do them
            for change in changes.split(' '):
                if change == '':
                    continue
                attr, values = split2(
                    change,
                    'Each change should be listed as attribute=value',
                    '=')
                if attr == 'style':
                    func = lambda vic: change_attr(vic, attr, values)
                elif attr == 'transform':
                    # prepend, so it is applied in the coordinates of the parent
                    func = lambda vic: vic.set(
                        attr, (values + ' ' + vic.get(attr, '')).strip())
                else:
                    raise ValueError("Don't yet handle attribute %s" % attr)

                for victim in victims:
                    func(victim)
    except (ValueError, RuntimeError, OSError, re.error,
            etree.LxmlError) as e:
        if options.verbose >= 4:
            raise
        raise SystemExit(
            ("%s:%d: %s" % (ifile, lineno, e)) if lineno else
            ("%s: %s" % (ifile, e)))


if __name__ == "__main__":
    ifile, options = parse_cmdline()
    svgtune(ifile, options)
